# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyPLM.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import os.path
import web_requests as wr
import controller as controller

class Ui_ProductListMaker(object):
    def setupUi(self, ProductListMaker):
        ProductListMaker.setObjectName("ProductListMaker")
        ProductListMaker.resize(681, 361)
        self.centralwidget = QtWidgets.QWidget(ProductListMaker)
        self.centralwidget.setObjectName("centralwidget")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(160, 10, 501, 171))
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")

        # model QComboBox

        self.modelBox = QtWidgets.QComboBox(self.mainFrame)
        self.modelBox.setEnabled(False)
        self.modelBox.setGeometry(QtCore.QRect(300, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.modelBox.setFont(font)
        self.modelBox.setObjectName("modelBox")
        self.modelBox.addItem("")
        self.modelBox.currentIndexChanged.connect(self.modelChange)

        # make QComboBox

        self.makeBox = QtWidgets.QComboBox(self.mainFrame)
        self.makeBox.setEnabled(False)
        self.makeBox.setGeometry(QtCore.QRect(100, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.makeBox.setFont(font)
        self.makeBox.setObjectName("makeBox")
        self.makeBox.addItem("")
        self.makeBox.currentIndexChanged.connect(self.makeChange)
        
        # year QComboBox

        self.yearBox = QtWidgets.QComboBox(self.mainFrame)
        self.yearBox.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.yearBox.setFont(font)
        self.yearBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yearBox.setObjectName("yearBox")
        self.yearBox.addItem("")
        self.yearBox.currentIndexChanged.connect(self.yearChange)

        # excel file label

        self.excelFileLabel = QtWidgets.QLabel(self.mainFrame)
        self.excelFileLabel.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.excelFileLabel.setObjectName("excelFileLabel")

        # submit button

        self.submitButton = QtWidgets.QPushButton(self.mainFrame)
        self.submitButton.setGeometry(QtCore.QRect(10, 120, 481, 31))
        self.submitButton.setDefault(False)
        self.submitButton.setFlat(False)
        self.submitButton.setObjectName("submitButton")
        self.submitButton.setEnabled(False)
        self.submitButton.clicked.connect(self.submitOnClick)

        self.widget = QtWidgets.QWidget(self.mainFrame)
        self.widget.setGeometry(QtCore.QRect(10, 70, 481, 31))
        self.widget.setObjectName("widget")

        # Browse horizontal layout

        self.BrowseFileLayout = QtWidgets.QHBoxLayout(self.widget)
        self.BrowseFileLayout.setContentsMargins(0, 0, 0, 0)
        self.BrowseFileLayout.setObjectName("BrowseFileLayout")

        # file path line

        self.fileLineEdit = QtWidgets.QLineEdit(self.widget)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.fileLineEdit.textChanged.connect(self.fileLineChange)
        self.BrowseFileLayout.addWidget(self.fileLineEdit)

        # browse button

        self.browseButton = QtWidgets.QPushButton(self.widget)
        self.browseButton.setObjectName("browseButton")
        self.browseButton.clicked.connect(self.getFile)
        self.BrowseFileLayout.addWidget(self.browseButton)

        # main title label

        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(20, 10, 131, 121))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mainLabel.setFont(font)
        self.mainLabel.setWordWrap(True)
        self.mainLabel.setObjectName("mainLabel")
        ProductListMaker.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProductListMaker)
        QtCore.QMetaObject.connectSlotsByName(ProductListMaker)

        # get years
        years = wr.getYears()
        for year in years:
            self.yearBox.addItem(year)

    def yearChange(self, i):
        currentYear = self.yearBox.currentText()
        if currentYear != 'YEAR':
        # update makes
            # remove old makes
            for i in range(1, self.makeBox.count()):
                self.makeBox.removeItem(1)
            # get new makes
            makes = wr.getMakes(currentYear.strip())
            for make in makes:
                self.makeBox.addItem(make)
            self.makeBox.setEnabled(True)
            self.modelBox.setEnabled(False)
        else:
            # disable other boxes
            self.makeBox.setEnabled(False)
            self.modelBox.setEnabled(False) 
        self.toggleReadyState()    

    def makeChange(self, i):
        currentYear = self.yearBox.currentText()
        currentMake = self.makeBox.currentText()
        if currentMake != 'MAKE':
        # update models
            # remove old models
            for i in range(1, self.modelBox.count()):
                self.modelBox.removeItem(1)
            # get new models
            models = wr.getModels(currentYear.strip(), currentMake)
            for model in models:
                self.modelBox.addItem(model)
            self.modelBox.setEnabled(True)
        else:
            self.modelBox.setEnabled(False)
        self.toggleReadyState()

    def modelChange(self, i):
        self.toggleReadyState()

    def fileLineChange(self):
        self.toggleReadyState()

    def getFile(self):
        fileName = QFileDialog.getOpenFileName(None, 'Open File',
            'C:\\', "Excel files (*.xlsx *.xls)")
        print(fileName)
        self.fileLineEdit.setText(fileName[0])

    def toggleReadyState(self):
        if self.yearBox.currentText() != 'YEAR' and self.makeBox.currentText() != 'MAKE' and self.modelBox.currentText() != 'MODEL':
            filePath = self.fileLineEdit.text()
            if os.path.exists(filePath) and (filePath.endswith('.xlsx') or filePath.endswith('.xls')):
                self.submitButton.setEnabled(True)
            else:
                self.submitButton.setEnabled(False)
                
        else:
            self.submitButton.setEnabled(False)

    def submitOnClick(self):
        currentYear = self.yearBox.currentText()
        currentMake = self.makeBox.currentText()
        currentModel = self.modelBox.currentText()
        specs = wr.getInfo(currentYear.strip(), currentMake, currentModel)
        path = self.fileLineEdit.text()
        print(specs)
        controller.match(specs, path)
        
        
    def retranslateUi(self, ProductListMaker):
        _translate = QtCore.QCoreApplication.translate
        ProductListMaker.setWindowTitle(_translate("ProductListMaker", "Product List Maker"))
        self.modelBox.setItemText(0, _translate("ProductListMaker", "MODEL"))
        self.makeBox.setItemText(0, _translate("ProductListMaker", "MAKE"))
        self.yearBox.setItemText(0, _translate("ProductListMaker", "YEAR"))
        self.excelFileLabel.setText(_translate("ProductListMaker", "Wheels Excel File:"))
        self.submitButton.setText(_translate("ProductListMaker", "Submit"))
        self.browseButton.setText(_translate("ProductListMaker", "Browse"))
        self.mainLabel.setText(_translate("ProductListMaker", "Product List Maker"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProductListMaker = QtWidgets.QMainWindow()
    ui = Ui_ProductListMaker()
    ui.setupUi(ProductListMaker)
    ProductListMaker.show()
    sys.exit(app.exec_())

